package com.crossover.techtrial.service;

import com.crossover.techtrial.model.HourlyElectricity;
import com.crossover.techtrial.repository.HourlyElectricityRepository;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import java.time.LocalDateTime;
import java.util.List;

/**
 * HourlyElectricityServiceImpl will handle electricity generated by a Panel.
 *
 * @author Crossover
 *
 */

public class HourlyElectricityServiceImpl implements HourlyElectricityService {

  private final HourlyElectricityRepository hourlyElectricityRepository;

  public HourlyElectricityServiceImpl(final HourlyElectricityRepository hourlyElectricityRepository) {
    this.hourlyElectricityRepository = hourlyElectricityRepository;
  }

  public HourlyElectricity save(HourlyElectricity hourlyElectricity) {
    return hourlyElectricityRepository.save(hourlyElectricity);
  }
  
  public Page<HourlyElectricity> getAllHourlyElectricityByPanelId(Long panelId, Pageable pageable) {
    return hourlyElectricityRepository.findAllByPanelIdOrderByReadingAtDesc(panelId, pageable);
  }

  @Override
  public List<HourlyElectricity> getHourlyElectricityByPanelIdBetweenDates(Long panelId, LocalDateTime startDate, LocalDateTime endDate) {
      return hourlyElectricityRepository.findAllByPanelIdAndReadingAtBetweenOrderByReadingAtDesc(panelId, startDate, endDate);
  }

}