package com.crossover.techtrial.model;

import com.fasterxml.jackson.annotation.JsonIgnore;
import lombok.*;

import java.io.Serializable;
import java.time.LocalDateTime;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;


/**
 * HourlyElectricity is responsible for electricity generated by a Panel in an hour.
 * 
 * @author Crossover
 *
 */

@Entity
@Table(name = "hourly_electricity")
@Data
@NoArgsConstructor
@AllArgsConstructor(access = AccessLevel.PRIVATE)
@Builder
public class HourlyElectricity implements Serializable {

  private static final long serialVersionUID = -575347909928592140L;
  
  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  private Long id;
  
  @JsonIgnore
  @ManyToOne
  @JoinColumn(name = "panel_id", referencedColumnName = "id")
  private Panel panel;
  
  @Column(name = "generated_electricity")
  private Long generatedElectricity;
  
  @Column(name = "reading_at")
  private LocalDateTime readingAt;

}
